### ISSUE TITLE
Blank comments

### ISSUE THREAD

**Issue by kennygrant** [kennygrant/gohackernews#24]
Occasionally seeing blank comments, would like to work out why.

**Comment by daenney** [comment]
I can explain what happened in my case. When I click reply on a comment the viewport of the page scrolls back to the top. If you enter a comment there, it's posted as a top comment, which wasn't my intention, I wanted to reply to yours. So I edited/blanked out my comment, hit reply again on yours and then scrolled back to the bottom where now a second field appears.

Oddly enough, even if you submit in there it sometimes seem to render it as a comment instead of a reply the first time around.

**Comment by daenney** [comment]
As far as I'm able to understand I think the behaviour is triggered by the fact that when clicking on the "reply" button a "#" is appended to the URL. Browsers interpret that as an anchor and since none seem to exist it just goes to the top of the page.
